#pragma once
#define MATRIX_ROWS 4
#define MATRIX_COLS 12
#define MATRIX_ROW_PINS { B7, F6, B6, C6 }
#define MATRIX_COL_PINS { E6, F0, F1, F4, F5, B0, B5, B4, D7, D6, D4, D3 }
#define DIODE_DIRECTION COL2ROW
#define DEBOUNCE 5
#define LOCKING_SUPPORT_ENABLE
#define LOCKING_RESYNC_ENABLE
#define ENCODERS_PAD_A { C6 }
#define ENCODERS_PAD_B { C7 }
#define ENCODER_RESOLUTION 4
#define MH_AUTO_BUTTONS_TIMEOUT 500
#define COMBO_TERM 30
//#define AUTO_SHIFT_TIMEOUT_PER_KEY
